INFO     root:log.py:39 正在测试tag.get
ERROR    root:log.py:43 60111